Environment Message
teamspatzenhirn/spatz_interfaces pull request #15
Opened 2022-01-14 16:33 UTC by authaldo

2022-01-14 16:45 UTC, Marco5de commented on msg/AbstractionInterface/Types/AbstractionCrosswalk.msg
> +geometry_msgs/Point[] corner_points
Hier auch Expansion verwenden?

2022-01-14 16:47 UTC, Marco5de commented on msg/AbstractionInterface/Types/AbstractionCrosswalk.msg
> +geometry_msgs/Point[] corner_points
```suggestion
Expansion corner_points
```

2022-01-14 16:52 UTC, Marco5de commented
Ich würde das soweit approven aber sollte sich vllt nochmal jemand anderes anschauen.

2022-01-14 18:02 UTC, ottojo requested changes

2022-01-14 18:02 UTC, ottojo commented on CMakeLists.txt
> +        "msg/AbstractionInterface/AbstractionInterfaceList.msg"
bitte liste wieder sortieren

2022-01-14 18:02 UTC, ottojo commented on msg/AbstractionInterface/Types/AbstractionBarredArea.msg
> +float64 dist_from_lane
kurzer kommentar was die felder machen

2022-01-14 18:02 UTC, ottojo commented on msg/AbstractionInterface/Types/AbstractionCrosswalk.msg
> +geometry_msgs/Point[] right_zone
auch hier kommentar (gibts in der c++ klasse schon, einfach klauen)

2022-01-14 18:02 UTC, ottojo commented on msg/AbstractionInterface/Types/AbstractionObstacle.msg
> +float64 max_theta
kommentar

2022-01-14 18:02 UTC, ottojo commented on msg/AbstractionInterface/Types/AbstractionObstacle.msg
> +float64 distance_to_spatz
das ändert sich doch wenn der spatz sich bewegt? warum existiert dieses feld?

2022-01-17 18:42 UTC, ottojo approved these changes

2022-01-18 10:22 UTC, merged